export const START_CHANNEL = "START_CHANNEL";
export const STOP_CHANNEL = "STOP_CHANNEL";

const USER_JOINED_CHANNEL = "USER_JOINED_CHANNEL"
const USER_LEFT_CHANNEL = "USER_LEFT_CHANNEL"

export const challengeEvents = {
    USER_JOINED_CHANNEL, USER_LEFT_CHANNEL
}