export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CHANGE_FIELD = "CHANGE_FIELD";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const SHOULD_RENDER_REGISTER = "SHOULD_RENDER_REGISTER";
