export const START_CHALLENGE_CHANNEL = "START_CHALLENGE_CHANNEL"
export const STOP_CHALLENGE_CHANNEL = "STOP_CHALLENGE_CHANNEL"

const USER_JOINED_CHANNEL = "USER_JOINED_CHANNEL"
const USER_LEFT_CHANNEL = "USER_LEFT_CHANNEL"
const GET_ONLINE_USERS = "GET_ONLINE_USERS"
const CHALLENGE_USER = "CHALLENGE_USER"
const ACCEPT_CHALLENGE = "ACCEPT_CHALLENGE"
const REFUSE_CHALLENGE = "REFUSE_CHALLENGE"

export const challengeEvents = {
    USER_JOINED_CHANNEL, USER_LEFT_CHANNEL, GET_ONLINE_USERS, CHALLENGE_USER, ACCEPT_CHALLENGE, REFUSE_CHALLENGE
}